version: "3.7"

services:

  #app_proxy:
    #environment:
      # The format here is: <app-id>_<docker-service-name>_1
      #APP_HOST: neodym-unifi-michivonah_server_1
      #APP_PORT: 8443
    
  server:
    image: michivonah/unifi-docker
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
      - 3478:3478/udp
      - 6789:6789
    volumes:
      - ./unifi:/unifi
    environment:
      - TZ=Europe/Zurich
    user: "1000:1000"
    init: true

